#!/usr/bin/env python

# A sample training component that trains a simple scikit-learn decision tree model.
# This implementation works in File mode and makes no assumptions about the input file names.
# Input is specified as CSV with a data point in each row and the labels in the first column.

from __future__ import print_function

import os
import hydra

os.environ["HYDRA_FULL_ERROR"] = "1"
import os.path as osp
import json
import pickle
import sys
import traceback

from src.configs.train_config import *
from src.training import train


# https://hydra.cc/docs/next/tutorials/structured_config/hierarchical_static_config
from omegaconf import DictConfig

import hydra


@hydra.main(config_path="conf", config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(cfg.pretty())


if __name__ == "__main__":
    my_app()
